module.exports = {
    apiDocs: "/_/docs",
    status: "/status",
    my_ip: "/my-ip",
    help: "/help",
    admin: {
        SELF: "/admin",
        ROOT: "/",
        COLLECTIONS: "/collections",
        COLLECTION_INFO: "/collection-info",
        COLLECTION_DATA: "/collection-data",
    },
    v1: {
        SELF: "/v1",
        ROOT: "/",
        AUTH: {
            SELF: "/auth",
            ROOT: "/",
            LOGIN: "/login",
            PASSWORD_LOGIN: "/login",
            REFRESH_LOGIN: "/login/refresh",
            REFRESH_LOGIN_TOKEN: "/login/refresh",
            PHONE: "/phone",
            EMAIL: "/email",
            TWOFA: "/2fa",
            TOTP: "/totp",
            PASSWORD: "/password",
            FORGOT_PASSWORD: "/password/forgot",
            VERIFY_FORGOT_PASSWORD: "/password/forgot/verify",
            LOGOUT: "/logout",
        },
        UPLOAD: {
            SELF: "/upload",
            ROOT: "/",
            PRESIGNED_URLS: "/presigned-urls",
            PRESIGNED_URL: "/presigned-url",
            TUS_VIDEO: "/tus-video",
        },
    },
};
